#!/usr/bin/python3

import sys

input = sys.argv

band_values = {

        "black": 0, "brown": 1, "red": 2, "orange": 3, "yellow": 4,

        "green": 5, "blue": 6, "violet": 7, "grey": 8, "white": 9

        }

band_multiples = {

        "silver": 0.01, "gold": 0.1, "black": 1, "brown": 10,

        "red": 100, "orange": 1000, "yellow": 10000, 

        "green": 100000, "blue": 1000000, "violet": 10000000, "grey": 100000000, "white": 1000000000

        }
values_tolerance = {

        "silver": 10, "gold": 5, "brown": 1, "red": 2, "green": 0.5,

        "blue": 0.25, "violet": 0.1

        }
def human_format(num):
    num = float('{:.3g}'.format(num))
    magnitude = 0
    while num >= 1000:
        magnitude += 1
        num /= 1000.0
    return '{}{}'.format('{:f}'.format(num).rstrip('0').rstrip('.'), ['', 'K', 'M', 'B', 'T'][magnitude])

if len(sys.argv)-1 < 3:
    print('Three bands required')
    exit()

#for tolerance, value in values_tolerance.iteritems():
if len(sys.argv) <= 5:
    resistance = int(str(band_values[input[1]]) + str(band_values[input[2]])) * band_multiples[input[3]] 
else: resistance = int(str(band_values[input[1]]) + str(band_values[input[2]]) + str(band_values[input[3]])) * band_multiples[input[4]]




print("Resistance:" + human_format(resistance))

if len(sys.argv) == 5: 
    print('Tolerance: ' + str(values_tolerance[input[4]]) + '%')
elif len(sys.argv) == 6: 
    print('Tolerance: ' + str(values_tolerance[input[5]]) + '%')

